name: Branch Protection Enforcement

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  enforce-staging-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        if: github.event_name == 'pull_request' && github.head_ref != 'staging'
        run: |
          echo "❌ ERROR: Pull requests to main must come from staging branch only!"
          echo "Current source branch: ${{ github.head_ref }}"
          echo "Expected source branch: staging"
          echo ""
          echo "Please merge your changes to staging first, then create a PR from staging to main."
          exit 1

      - name: Check direct push to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]'
        run: |
          echo "❌ ERROR: Direct pushes to main branch are not allowed!"
          echo "Please use the staging → main workflow:"
          echo "1. Push changes to staging branch"
          echo "2. Create PR from staging to main"
          echo "3. Merge PR after review"
          exit 1

      - name: Workflow summary
        if: success()
        run: |
          echo "✅ Branch protection rules passed"
          echo "PR from staging to main is allowed" 