name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build application
        run: npm run build
        env:
          DATABASE_URL: postgresql://placeholder:placeholder@localhost:5432/placeholder
          JWT_SECRET: build-time-placeholder
          ENCRYPTION_KEY: build-time-placeholder-key-for-testing
          NEXT_PUBLIC_BASE_URL: https://tc9-migration-tool.fly.dev
          NEXT_PUBLIC_APP_URL: https://tc9-migration-tool.fly.dev

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set production secrets
        run: |
          flyctl secrets set \
            DATABASE_URL="postgres://tc9_migration_tool:fEV6CJGnjocBXTW@tc9-migration-tool-db.flycast:5432/tc9_migration_tool?sslmode=disable" \
            NODE_ENV="production" \
            BETTER_AUTH_SECRET="${{ secrets.BETTER_AUTH_SECRET }}" \
            BETTER_AUTH_URL="https://tc9-migration-tool.fly.dev" \
            NEXT_PUBLIC_APP_URL="https://tc9-migration-tool.fly.dev" \
            NEXT_PUBLIC_BASE_URL="https://tc9-migration-tool.fly.dev" \
            SALESFORCE_PRODUCTION_CLIENT_ID="${{ secrets.SALESFORCE_PRODUCTION_CLIENT_ID }}" \
            SALESFORCE_PRODUCTION_CLIENT_SECRET="${{ secrets.SALESFORCE_PRODUCTION_CLIENT_SECRET }}" \
            SALESFORCE_SANDBOX_CLIENT_ID="${{ secrets.SALESFORCE_SANDBOX_CLIENT_ID }}" \
            SALESFORCE_SANDBOX_CLIENT_SECRET="${{ secrets.SALESFORCE_SANDBOX_CLIENT_SECRET }}" \
            ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY }}" \
            JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            SENTRY_DSN="${{ secrets.SENTRY_DSN }}" \
            NEXT_PUBLIC_SENTRY_DSN="${{ secrets.SENTRY_DSN }}" \
            --app tc9-migration-tool
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Verify production secrets
        run: |
          flyctl secrets list --app tc9-migration-tool
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io Production
        run: |
          flyctl deploy --app tc9-migration-tool --strategy=rolling
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Ensure app is running
        run: |
          echo "🔄 Ensuring app is running before migrations..."
          flyctl machine list --app tc9-migration-tool --json | jq -r '.[] | select(.state=="stopped") | .id' | xargs -I {} flyctl machine start {} --app tc9-migration-tool
          
          # Wait a bit for the scale command to take effect
          sleep 10
          
          # Wait for app to be ready
          max_attempts=15
          attempt=1
          
          while [ $attempt -le $max_attempts ]; do
            echo "⏳ Attempt $attempt/$max_attempts: Checking if app is ready..."
            
            # Get detailed status
            echo "📊 Current app status:"
            flyctl status --app tc9-migration-tool || true
            
            if flyctl status --app tc9-migration-tool | grep -q "started"; then
              echo "✅ App is running"
              break
            else
              echo "⏳ App not ready yet, waiting 45 seconds..."
              sleep 45
            fi
            
            attempt=$((attempt + 1))
            
            if [ $attempt -gt $max_attempts ]; then
              echo "❌ App failed to start after $max_attempts attempts"
              echo "📊 Final app status:"
              flyctl status --app tc9-migration-tool || true
              echo "🔍 App logs:"
              flyctl logs --app tc9-migration-tool || true
              exit 1
            fi
          done
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Run database migrations
        run: |
          echo "🔄 Running database migrations..."
          max_attempts=3
          attempt=1
          
          while [ $attempt -le $max_attempts ]; do
            echo "📊 Migration attempt $attempt/$max_attempts..."
            
            if flyctl ssh console --app tc9-migration-tool -C "npx prisma migrate deploy"; then
              echo "✅ Database migrations completed successfully"
              break
            else
              echo "⚠️ Migration failed, retrying in 15 seconds..."
              sleep 15
              attempt=$((attempt + 1))
              
              if [ $attempt -gt $max_attempts ]; then
                echo "❌ Migrations failed after $max_attempts attempts"
                echo "🔧 You may need to run migrations manually:"
                echo "flyctl ssh console --app tc9-migration-tool -C 'npx prisma migrate deploy'"
                exit 1
              fi
            fi
          done
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Health check
        run: |
          echo "🏥 Performing health check..."
          sleep 30
          
          max_attempts=3
          attempt=1
          
          while [ $attempt -le $max_attempts ]; do
            echo "🔍 Health check attempt $attempt/$max_attempts..."
            
            if curl -f --max-time 30 https://tc9-migration-tool.fly.dev/api/health; then
              echo "✅ Health check passed"
              break
            else
              echo "⚠️ Health check failed, retrying in 15 seconds..."
              sleep 15
              attempt=$((attempt + 1))
              
              if [ $attempt -gt $max_attempts ]; then
                echo "❌ Health check failed after $max_attempts attempts"
                echo "⚠️ Deployment completed but app may not be responding correctly"
                break
              fi
            fi
          done

      - name: Smoke tests
        run: |
          # Test critical endpoints
          curl -f https://tc9-migration-tool.fly.dev/ || exit 1
          curl -f https://tc9-migration-tool.fly.dev/api/health || exit 1

      - name: Create GitHub release
        if: success()
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Automated production deployment
            
            **Deployed at:** ${{ github.event.head_commit.timestamp }}
            **Commit:** ${{ github.sha }}
            **Author:** ${{ github.event.head_commit.author.name }}
            
            **Changes:**
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ Production deployment successful: https://tc9-migration-tool.fly.dev"
          echo "🏷️ Release: v${{ github.run_number }}"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Production deployment failed"
          echo "🔍 Check logs and rollback if necessary"
          exit 1 